#!/bin/bash

torrent_name=internet_raytracing_competition_archive_full
trackers=http://tracker.opentrackr.org:1337/announce,udp://opentracker.i2p.rocks:6969/announce,udp://tracker1.bt.moack.co.kr:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.dler.org:6969/announce,udp://p4p.arenabg.com:1337/announce,udp://open.stealth.si:80/announce,udp://open.demonii.com:1337/announce,udp://movies.zsw.ca:6969/announce,udp://explodie.org:6969/announce,udp://exodus.desync.com:6969/announce,https://tracker2.ctix.cn:443/announce,https://tracer1.520.jp:443/announce,https://tracker.lilithraws.org:443/announce,https://tr.burnabyhighstar.com:443/announce,http://tracker.mywaifu.best:6969/announce,udp://uploads.gamecoast.net:6969/announce,udp://tracker2.dler.org:80/announce,udp://tracker1.myporn.club:9337/announce,udp://tracker.theoks.net:6969/announce,udp://tracker.srv00.com:6969/announce,udp://tracker.publictracker.xyz:6969/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.leech.ie:1337/announce,udp://tracker.joybomb.tw:6969/announce,dp://tracker.jonaslsa.com:6969/announce,udp://tracker.filemail.com:6969/announce,udp://tracker.ddunlimited.net:6969/announce,udp://tracker.bitsearch.to:1337/announce,udp://tracker.auctor.tv:6969/announce,udp://tracker.artixlinux.org:6969/announce,udp://tracker.army:6969/announce,udp://tracker.altrosky.nl:6969/announce,udp://tracker.4.babico.name.tr:3131/announce,udp://tracker-udp.gbitt.info:80/announce,udp://tr.bangumi.moe:6969/announce,udp://torrents.artixlinux.org:6969/announce,udp://thouvenin.cloud:6969announce,udp://tamas3.ynh.fr:6969/announce,udp://sanincode.com:6969/announce,udp://run.publictracker.xyz:6969/announce,udp://run-2.publictracker.xyz:6969/announce,udp://public.tracker.vraphim.com:6969/announce,udp://public.publictracker.xyz:6969/announce,udp://psyco.fr:6969/announce,udp://open.free-tracker.ga:6969/announce,udp://open.dstud.io:6969/announce,udp://new-line.net:6969/announce,udp://moonburrow.club:6969/announce,udp://mail.artixlinux.org:6969/announce,udp://htz3.noho.st:6969/announce,udp://fh2.mp-gaming.com:6969/announce,udp://epider.me:6969/announce,udp://download.nerocloud.me:6969/announce,udp://concen.org:6969/announce,udp://carr.codes:6969/announce,udp://bt2.archive.org:6969/announce,udp://bt1.archive.org:6969/announce,udp://bt.ktrackers.com:6666/announce,udp://black-bird.ynh.fr:6969/announce,udp://aarsen.me:6969/announce,https://tracker.tamersunion.org:443/announce,https://tracker.kuroy.me:443/announce,https://tracker.gbitt.info:443/announce,https://1337.abcvg.info:443/announce,http://wepzoe.net:6969/announce,http://tracker.files.fm:6969/announce,http://tracker.bt4g.com:2095/announce,http://open.acgnxtracker.com:80/announce,http://bt.okmp3.ru:2710/announce
data_src=data/ftp.irtc.org/internet_raytracing_competition_archive_full

mktorrent -v \
  --output=${torrent_name}.torrent \
  --name="${torrent_name}" \
  --announce="${trackers}" \
  ${data_src}
